-- Tables deletion
DROP TABLE IF EXISTS GUILD_MISSION;
DROP TABLE IF EXISTS GUILD_MEMBER;
DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS CONVERSATION_PARTICIPANT;
DROP TABLE IF EXISTS CONVERSATION;
DROP TABLE IF EXISTS NOTIFICATION;
DROP TABLE IF EXISTS INVITATION;
DROP TABLE IF EXISTS MISSION_PAYMENT;
DROP TABLE IF EXISTS MISSION_PARTICIPATION;
DROP TABLE IF EXISTS REVIEW;
DROP TABLE IF EXISTS TAG;
DROP TABLE IF EXISTS PAYMENT_METHOD;
DROP TABLE IF EXISTS ROLE; 
DROP TABLE IF EXISTS MISSION;
DROP TABLE IF EXISTS GUILD;
DROP TABLE IF EXISTS APP_USER;


-- Special options creation
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS postgis;

-- Tables creation
CREATE TABLE APP_USER (
	uid SERIAL PRIMARY KEY,
	username VARCHAR(20) NOT NULL UNIQUE,
	email VARCHAR(100) UNIQUE,
	firebase_uid VARCHAR(255) NOT NULL UNIQUE,
	description VARCHAR(500),
	name VARCHAR(50),
	surnames VARCHAR(100),
	location geography(Point, 4326),
	avatar VARCHAR(255),
	configuration JSONB NOT NULL DEFAULT '{"show_missions_to_others": true}'::jsonb,
	rating NUMERIC(3,2) NOT NULL DEFAULT 0 CHECK (rating >= 0 AND rating <= 5),
	stripe_customer_id VARCHAR(255),
  	stripe_connected_id VARCHAR(255)
);

CREATE TABLE PAYMENT_METHOD (
	payment_method VARCHAR(100) NOT NULL,
	uid INT NOT NULL,	
	FOREIGN KEY (uid) REFERENCES APP_USER(uid),
	PRIMARY KEY(payment_method, uid)
);

CREATE TABLE MISSION (
	mid SERIAL PRIMARY KEY,
	publication_date TIMESTAMP NOT NULL,
	title VARCHAR(100) NOT NULL,
	description VARCHAR(1000) NOT NULL,
	total_vacancies INT NOT NULL,
	occupied_vacancies INT NOT NULL,
	location geography(Point, 4326),
	total_payment NUMERIC NOT NULL,
	status VARCHAR(30) NOT NULL CHECK (status IN (
		'DRAFT',
		'OPENED',
		'CLOSED',
		'IN_PROGRESS',
		'REOPENED',
		'CANCELLING',
		'CANCELLED',
		'DELETED',
		'IN_DISPUTE',
		'FINISHED')),
	completion_date TIMESTAMP,
	owner_id INT NOT NULL,
	FOREIGN KEY (owner_id) REFERENCES APP_USER(uid)
);

CREATE TABLE CONVERSATION (
	cid SERIAL PRIMARY KEY,
	type VARCHAR(20) NOT NULL CHECK (type IN ('private', 'mission')),
	mission_id INT UNIQUE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	closed_at TIMESTAMP,
	FOREIGN KEY (mission_id) REFERENCES MISSION(mid)
);

CREATE TABLE CONVERSATION_PARTICIPANT (
	conversation_id INT NOT NULL,
	user_id INT NOT NULL,
	joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	left_at TIMESTAMP,
	last_read_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (conversation_id, user_id),
	FOREIGN KEY (conversation_id) REFERENCES CONVERSATION(cid) ON DELETE CASCADE,
	FOREIGN KEY (user_id) REFERENCES APP_USER(uid) ON DELETE CASCADE
);

CREATE TABLE MESSAGE (
	mid SERIAL PRIMARY KEY,
	conversation_id INT NOT NULL,
	sender_id INT NOT NULL,
	content VARCHAR(1000) NOT NULL CHECK (LENGTH(TRIM(content)) > 0),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (conversation_id) REFERENCES CONVERSATION(cid) ON DELETE CASCADE,
	FOREIGN KEY (sender_id) REFERENCES APP_USER(uid)
);

CREATE TABLE REVIEW (
	id SERIAL PRIMARY KEY,
	comment VARCHAR(500),
	rating NUMERIC(2,1) NOT NULL CHECK (rating >= 1 AND rating <= 5),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MISSION_PARTICIPATION (
	id SERIAL PRIMARY KEY,
	mid INT NOT NULL,
	adventurer_id INT,
	title VARCHAR(50),
	description VARCHAR(500),
  	monetary_reward NUMERIC NOT NULL,
	amount_paid NUMERIC NOT NULL,
	payment_status VARCHAR(20) DEFAULT 'UNPAID' CHECK (payment_status IN (
		'UNPAID', 
		'PAID', 
		'PARTIALLY_PAID', 
		'PARTIALLY_REFUNDED',
		'LIQUIDATED', 
		'REFUNDED'
		)),
	status VARCHAR(20) NOT NULL DEFAULT 'EMPTY' CHECK (status IN (
		'EMPTY',
		'JOINED',
		'PENDING_PAYMENT',
		'IN_PROGRESS',
		'SUBMITTED',
		'ACCEPTED',
		'REJECTED',
		'IN_DISPUTE',
		'RELEASED'
	)),
	owner_review_id INT UNIQUE,
	adventurer_review_id INT UNIQUE,
	FOREIGN KEY (mid) REFERENCES MISSION(mid),
	FOREIGN KEY (adventurer_id) REFERENCES APP_USER(uid),
	FOREIGN KEY (owner_review_id) REFERENCES REVIEW(id),
	FOREIGN KEY (adventurer_review_id) REFERENCES REVIEW(id)
);

CREATE TABLE MISSION_PAYMENT (
	pid SERIAL PRIMARY KEY,
	mid INT NOT NULL,
	vacancy_id INT NOT NULL,
	sender_id INT NOT NULL,
	receiver_id INT NOT NULL,
	stripe_transaction_id VARCHAR(255) NOT NULL,
	transaction_type VARCHAR(255) NOT NULL CHECK (transaction_type IN(
		'INITIAL_FUNDING',
		'NEW_ADVENTURER_FUNDING',
		'NEGOTIATION_EXTRA',
		'NEGOTIATION_REFUND',
		'CANCELLATION_COMPENSATION',
		'PAYOUT'
	)),
	amount_paid NUMERIC NOT NULL,
	amount_refunded NUMERIC NOT NULL,
	status VARCHAR(25) NOT NULL DEFAULT 'SUCCEEDED' CHECK (status IN ('SUCCEEDED', 'PARTIALLY_REFUNDED', 'REFUNDED')),
	created_at TIMESTAMP NOT NULL,
	FOREIGN KEY (mid) REFERENCES MISSION(mid),
	FOREIGN KEY (vacancy_id) REFERENCES MISSION_PARTICIPATION(id),
	FOREIGN KEY (sender_id) REFERENCES APP_USER(uid),
	FOREIGN KEY (receiver_id) REFERENCES APP_USER (uid)
);


CREATE TABLE NOTIFICATION (
	nid SERIAL PRIMARY KEY,
	date TIMESTAMP NOT NULL,
	seen BOOLEAN NOT NULL DEFAULT FALSE,
	type VARCHAR(50) NOT NULL CHECK (type IN ('INVITATION', 'MISSION')),
	kind VARCHAR(20) NOT NULL DEFAULT 'ACTIONABLE' CHECK (kind IN ('INFORMATIONAL', 'ACTIONABLE')),
	action VARCHAR(50) NOT NULL DEFAULT 'MISSION_INVITE' CHECK (action IN (
		'JOIN_REQUEST',
		'MISSION_INVITE',
		'PARTICIPATION_REVIEW',
		'PARTICIPATION_REJECTION_RESPONSE',
		'PARTICIPATION_APPROVED',
		'PARTICIPATION_DISPUTED',
		'MISSION_EDIT',
		'MISSION_CLOSE', --- Mission has been closed for adventurers, but its not payed
		'MISSION_START', --- Mission has been payed, so it starts
		'MISSION_UNJOIN',
		'MISSION_DELETE',
		'MISSION_CANCEL',
		'MISSION_REOPEN'
	)),
	status VARCHAR(20) CHECK (status IS NULL OR status IN ('PENDING','ACCEPTED','REJECTED','DISPUTED')),
	message VARCHAR(500),
	sender_id INT NOT NULL,
	recipient_id INT NOT NULL,
	payload JSONB NOT NULL DEFAULT '{}'::jsonb,
	FOREIGN KEY (sender_id) REFERENCES APP_USER(uid),
	FOREIGN KEY (recipient_id) REFERENCES APP_USER (uid)
);

INSERT INTO app_user(username, email, firebase_uid, description, name, surnames) VALUES('Hermyx', 'hermyx@hermyx.com', '---', 'Hermyx admin account.', 'Hermyx', 'account');
