export const MISSION_LIFE_CYCLE = {
  OPENED: {
    ID: 'OPENED',
    LABEL: 'Opened',
    CAN_EDIT: true,
    CAN_DELETE: true,
    CAN_CANCEL: false,
    CAN_ACCEPT_ADVENTURERS: true,
    CAN_DELETE_ADVENTURERS: true,
    ADVENTURERS_CAN_UNJOIN: true,
    VALID_NEXT_STATES: ['CLOSED', 'DELETED'],
  },
  CLOSED: {
    ID: 'CLOSED',
    LABEL: 'Closed',
    CAN_EDIT: true,
    CAN_DELETE: true,
    CAN_CANCEL: false,
    CAN_ACCEPT_ADVENTURERS: false,
    CAN_DELETE_ADVENTURERS: false,
    ADVENTURERS_CAN_UNJOIN: false,
    VALID_NEXT_STATES: ['PENDING_PAYMENT', 'DELETED'],
  },
  PENDING_PAYMENT: {
    ID: 'PENDING_PAYMENT',
    LABEL: 'Pending payment',
    CAN_EDIT: true,
    CAN_DELETE: false,
    CAN_CANCEL: true,
    CAN_ACCEPT_ADVENTURERS: false,
    CAN_DELETE_ADVENTURERS: false,
    ADVENTURERS_CAN_UNJOIN: false,
    VALID_NEXT_STATES: ['IN_PROGRESS', 'CANCELLING'],
  },
  IN_PROGRESS: {
    ID: 'IN_PROGRESS',
    LABEL: 'In progress',
    CAN_EDIT: true,
    CAN_DELETE: false,
    CAN_CANCEL: true,
    CAN_ACCEPT_ADVENTURERS: false,
    CAN_DELETE_ADVENTURERS: false,
    ADVENTURERS_CAN_UNJOIN: false,
    VALID_NEXT_STATES: ['FINISHED', 'IN_DISPUTE', 'REOPENED', 'CANCELLING'],
  },
  REOPENED: {
    ID: 'REOPENED',
    LABEL: 'Reopened',
    CAN_EDIT: true,
    CAN_DELETE: false,
    CAN_CANCEL: true,
    CAN_ACCEPT_ADVENTURERS: true,
    CAN_DELETE_ADVENTURERS: false,
    ADVENTURERS_CAN_UNJOIN: false,
    VALID_NEXT_STATES: ['PENDING_PAYMENT', 'CANCELLING'],
  },
  CANCELLING: {
    ID: 'CANCELLING',
    LABEL: 'Cancelling',
    CAN_EDIT: false,
    CAN_DELETE: false,
    CAN_CANCEL: false,
    CAN_ACCEPT_ADVENTURERS: false,
    CAN_DELETE_ADVENTURERS: false,
    ADVENTURERS_CAN_UNJOIN: false,
    VALID_NEXT_STATES: ['CANCELLED'],
  },
  CANCELLED: {
    ID: 'CANCELLED',
    LABEL: 'Cancelled',
    CAN_EDIT: false,
    CAN_DELETE: false,
    CAN_CANCEL: false,
    CAN_ACCEPT_ADVENTURERS: false,
    CAN_DELETE_ADVENTURERS: false,
    ADVENTURERS_CAN_UNJOIN: false,
    VALID_NEXT_STATES: [],
  },
  DELETED: {
    ID: 'DELETED',
    LABEL: 'Deleted',
    CAN_EDIT: false,
    CAN_DELETE: false,
    CAN_CANCEL: false,
    CAN_ACCEPT_ADVENTURERS: false,
    CAN_DELETE_ADVENTURERS: false,
    ADVENTURERS_CAN_UNJOIN: false,
    VALID_NEXT_STATES: [],
  },
  IN_DISPUTE: {
    ID: 'IN_DISPUTE',
    LABEL: 'In dispute',
    CAN_EDIT: true,
    CAN_DELETE: false,
    CAN_CANCEL: true,
    CAN_ACCEPT_ADVENTURERS: false,
    CAN_DELETE_ADVENTURERS: false,
    ADVENTURERS_CAN_UNJOIN: false,
    VALID_NEXT_STATES: ['REOPENED', 'CANCELLING'],
  },
  FINISHED: {
    ID: 'FINISHED',
    LABEL: 'Finished',
    CAN_EDIT: false,
    CAN_DELETE: false,
    CAN_CANCEL: false,
    CAN_ACCEPT_ADVENTURERS: false,
    CAN_DELETE_ADVENTURERS: false,
    ADVENTURERS_CAN_UNJOIN: false,
    VALID_NEXT_STATES: [],
  },
};

export const VACANCY_LIFE_CYCLE = {
  EMPTY: {
    ID: 'EMPTY',
    LABEL: 'Empty',
    VALID_NEXT_STATES: ['JOINED'],
  },
  JOINED: {
    ID: 'JOINED',
    LABEL: 'Joined',
    VALID_NEXT_STATES: ['EMPTY', 'PENDING_PAYMENT'],
  },
  PENDING_PAYMENT: {
    ID: 'PENDING_PAYMENT',
    LABEL: 'Pending payment',
    VALID_NEXT_STATES: ['IN_PROGRESS'],
  },
  IN_PROGRESS: {
    ID: 'IN_PROGRESS',
    LABEL: 'In progress',
    VALID_NEXT_STATES: ['SUBMITTED'],
  },
  SUBMITTED: {
    ID: 'SUBMITTED',
    LABEL: 'Submitted',
    VALID_NEXT_STATES: ['ACCEPTED', 'REJECTED', 'IN_DISPUTE'],
  },
  ACCEPTED: {
    ID: 'ACCEPTED',
    LABEL: 'Accepted',
    VALID_NEXT_STATES: ['RELEASED'],
  },
  REJECTED: {
    ID: 'REJECTED',
    LABEL: 'Rejected',
    VALID_NEXT_STATES: ['IN_PROGRESS', 'IN_DISPUTE'],
  },
  IN_DISPUTE: {
    ID: 'IN_DISPUTE',
    LABEL: 'In dispute',
    VALID_NEXT_STATES: ['IN_PROGRESS'],
  },
  RELEASED: { ID: 'RELEASED', LABEL: 'Released', VALID_NEXT_STATES: [] },
};
